CREATE OR REPLACE TRIGGER TRIG_YJ_WARNING_FORECAST BEFORE INSERT ON "YJ_WARNING_FORECAST" -- 针对这个预测表
FOR EACH ROW
WHEN (NEW ."DBID" IS NULL)
BEGIN
	SELECT
		SEQ_YJ_WARNING_FORECAST.nextval INTO : NEW ."DBID"
	FROM
		dual ;
END ;