-- Create table
create table AD_DJ_FLOW
(
  DBID    NUMBER(19) primary key not null,
  CELL    VARCHAR2(255 CHAR),
  DEVCODE VARCHAR2(255 CHAR),
  INSDATA VARCHAR2(255 CHAR),
  LOGTIME DATE,
  NEGDATA VARCHAR2(255 CHAR),
  NETDATA VARCHAR2(255 CHAR),
  POSDATA VARCHAR2(255 CHAR),
  SIGNAL  VARCHAR2(255 CHAR),
  STATUS  VARCHAR2(255 CHAR),
  UPTIME  DATE
)