create table AD_SL_NOISE
(
  DBID          NUMBER(19) primary key not null,
  CELL          VARCHAR2(255 CHAR),
  DBEGIN        VARCHAR2(255 CHAR),
  DCOUNT        VARCHAR2(255 CHAR),
  DINTERVAL     VARCHAR2(255 CHAR),
  DENSEDATA     VARCHAR2(255 CHAR),
  DSTID         VARCHAR2(255 CHAR),
  LBEGIN        VARCHAR2(255 CHAR),
  LCOUNT        VARCHAR2(255 CHAR),
  LINTERVAL     VARCHAR2(255 CHAR),
  LOGTIME       DATE,
  LOOSEDATA     VARCHAR2(255 CHAR),
  SIGNAL        VARCHAR2(255 CHAR),
  DEVCODE       VARCHAR2(255 CHAR),
  STATUS        VARCHAR2(255 CHAR),
  TAGID         VARCHAR2(255 CHAR),
  UPTIME        DATE,
  WIRELESSCLOSE VARCHAR2(255 CHAR),
  WIRELESSOPEN  VARCHAR2(255 CHAR)
)