create table XT_RQ_PERIOD
(
  DBID        NUMBER(19) primary key not null,
  ADDRESS     VARCHAR2(255 CHAR),
  CELL        VARCHAR2(255 CHAR),
  FLOW        VARCHAR2(255 CHAR),
  INPRESS     VARCHAR2(255 CHAR),
  LOGTIME     DATE,
  OUTPRESS    VARCHAR2(255 CHAR),
  STRENGTH    VARCHAR2(255 CHAR),
  TEMPERATURE VARCHAR2(255 CHAR),
  UPTIME      DATE
)